name: Retrain (Full CI/CD)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # Every Monday 6 AM UTC

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 build

      # --- LINT ---
      - name: Lint code with flake8
        run: |
          flake8 src scripts --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 src scripts --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      # --- TESTS ---
      - name: Run tests
        run: |
          pytest -q || echo "⚠️ Tests failed or none found, continuing..."

      # --- BUILD DOCKER IMAGE ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64

      # --- TRAIN / EVALUATE / PROMOTE ---
      - name: Run training
        run: python scripts/train.py

      - name: Run evaluation
        run: python scripts/evaluate.py

      - name: Run promotion
        run: python scripts/promote.py

      # --- UPLOAD ARTIFACTS ---
      - name: Upload MLflow runs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: /tmp/mlruns
