name: Retrain (Full CI/CD)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"  # every Monday 6 AM UTC

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: python scripts/train.py

      - name: Run evaluation
        run: python scripts/evaluate.py

      - name: Promote model
        run: python scripts/promote.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            artifacts/
            mlruns/
