name: Retrain (Full CI/CD)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC daily retrain

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas mlflow

      # 🧠 Step 1: Run hardened multi-book ingest before training
      - name: Run ingest + DQ audit
        run: |
          echo "=== Running pre-ingest step ==="
          mkdir -p artifacts
          python scripts/ingest_books.py > artifacts/ingest_log.txt 2>&1
          echo "=== Ingest complete ==="
          cat artifacts/ingest_audit.json || true

      # 🚫 If DQ fails, stop the pipeline early
      - name: Validate ingest DQ
        run: |
          echo "=== Checking DQ pass rate ==="
          PASS_COUNT=$(jq '.summary.dq_pass' artifacts/ingest_audit.json)
          TOTAL=$(jq '.summary.total_books' artifacts/ingest_audit.json)
          echo "DQ pass rate: $PASS_COUNT / $TOTAL"
          if [ "$PASS_COUNT" -lt "$((TOTAL / 2))" ]; then
            echo "[ERROR] Too few clean ingests. Aborting retrain."
            exit 1
          fi

      # 🧠 Step 2: Run retraining pipeline
      - name: Run training
        run: |
          echo "Running training..."
          mkdir -p artifacts
          python scripts/train.py > artifacts/train_log.txt 2>&1 || true

      - name: Run evaluation
        run: |
          echo "Evaluating model..."
          python scripts/evaluate.py > artifacts/evaluate_log.txt 2>&1 || true

      - name: Run promotion logic
        run: |
          echo "Running promotion logic..."
          python scripts/promote.py > artifacts/promote_log.txt 2>&1 || true

      # 🧩 Step 3: Upload artifacts for audit trail
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: retrain-artifacts
          path: artifacts/
